version: "2.4"

services:
  api:
    env_file:
      - ./.production.env
    volumes:
      - api-modules:/api/node_modules
  ui:
    env_file:
      - ./.production.env
    volumes:
      - ui-modules:/ui/node_modules
