version: "2.4"

services:
  api:
    container_name: key_api
    image: key_api
    env_file:
      - ./.env
    volumes:
      - ./api/util:/util
      - ./api/api.js:/api.js
      - api-modules:/api/node_modules
    build:
      context: .
      dockerfile: api.Dockerfile
      target: local-dev
    ports:
      - "9999:9999"
    restart: always
    networks:
      - b_sharp
  ui:
    container_name: key_ui
    image: key_ui
    env_file:
      - ./.env
    volumes:
      - ./ui/public:/public
      - ./ui/src:/src
      - ui-modules:/ui/node_modules
    build:
      context: .
      dockerfile: ui.Dockerfile
      target: local-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    ports:
      - "5000:5000"
    restart: always
    networks:
      - b_sharp
volumes:
  api-modules:
  ui-modules:
networks:
  b_sharp:
    name: b_sharp
