version: "2.4"

services:
  api:
    container_name: key_api
    image: key_api
    env_file:
      - ./.env
    volumes:
      - ./api/src:/service/src
      - api-modules:/service/node_modules
    build:
      context: .
      dockerfile: api.Dockerfile
      target: local-dev
    ports:
      - "9999:9999"
    restart: always
    networks:
      - b_sharp
  ui:
    container_name: key_ui
    image: key_ui
    env_file:
      - ./.env
    volumes:
      - ./ui/public:/service/public
      - ./ui/src:/service/src
      - ui-modules:/service/node_modules
    build:
      context: .
      dockerfile: ui.Dockerfile
      target: local-dev
    ports:
      - "5000:5000"
    restart: always
    networks:
      - b_sharp
volumes:
  api-modules:
  ui-modules:
networks:
  b_sharp:
    name: b_sharp
