version: "2.4"

services:
  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9999"
    restart: always
    networks:
      - b_sharp

networks:
  b_sharp:
    name: b_sharp
